### ISSUE TITLE
训练过程中的缓存机制

### ISSUE THREAD

**Issue by raozhongyu** [opendilab/DOS#10]
非常感谢博主的论文，深受启发，有一些问题想咨询一下博主
1）论文中的 Interaction modeling 是图神经网络吗？能否进一步详细介绍
2）训练过程中的时间步长是多少呢？假设步长为4，是每一帧都有一个输出和loss作梯度下降，还是只采用最后一帧的输出作梯度下降？
感谢博主

**Comment by deepcs233** [comment]
1) 这里就是普通的graph attention network
2）这在Experiment Setup里有介绍，每一帧都有loss。训练的时候是把连续8帧放在一起训练的。

**Comment by raozhongyu** [comment]
感谢博主
