### ISSUE TITLE
内存缓存机制

### ISSUE THREAD

**Issue by a1wj1** [opendilab/DOS#3]
![1688440370376](https://github.com/opendilab/DOS/assets/38905689/7598410c-e21f-4888-b874-bc944f47cf40)

Hi，我对这段描述不是很理解，主要有3点：
1. the last memory frame is full，这句话指的什么意思？是代表内存满了吗？可是下文也有提到帧数满废弃旧内存的情况。
2.  initialize one new frame with the zero vector and set it as the last frame to store new features. 这句话的工程性逻辑我没太理解，请问可以再解释一下吗，麻烦了
3. When the number of frames reachesthe limit Tl, the obsolete memory will be removed. 请问这里的obsolete memory是怎么定义的？就是直接把long-term 内存的原先的都清理掉吗？

**Comment by deepcs233** [comment]
Hi!
1. 是的，这是代表long term memory已满，并会丢弃过时的feature。下文也有提到可能是指的short term memory。这是两个不同的模块。
2. 因为long term memory并不会复制一帧中的所有feature进行存储，会挑选出一部分有价值的feature进行存储。所以在long term memory进行存储之前，会初始化一整帧空的memory进行存储。例如一帧的大小是50x50x256，那就有2500个位置可以存储被挑选过的feature。等这2500个位置存储满了，便会初始化一个空的帧进行存储。帧数
3. 达到上限之后，便会丢弃旧的帧。
4. 对的，可以看对上一个问题的解答。

**Comment by a1wj1** [comment]
感谢！
